// Rewrite the instructions in your own words
// create a variable for all the acronyms
// make each acronyms generate when given a particular phrase
// all acronyms when generated must be in all caps

// Write the objectives and the tests
// create a list for all the acronyms with a given phrase
// 

// Write the pseudocode



// paste your JS generated by blockly below here
